export const pathogen = {
    Alternaria_alternata: 'Alternaria alternata',
    Ascosphaera_apis: 'Ascosphaera apis',
    Acute_bee_paralysis_virus: 'Acute bee paralysis virus',
    Avian_coronavirus: 'Avian coronavirus',
    Aspergillus_flavus: 'Aspergillus flavus',
    Aspergillus_fumigatus: 'Aspergillus fumigatus',
    Alcelaphine_gammaherpesvirus_2: 'Alcelaphine gammaherpesvirus 2',
    Anaplasma_marginale: 'Anaplasma marginale',
    Aspergillus_niger: 'Aspergillus niger',
    Aspergillus_parasiticus: 'Aspergillus parasiticus',
    African_swine_fever_virus: 'African swine fever virus',
    Aspergillus_terreus: 'Aspergillus terreus',
    Actinomyces_viscosus: 'Actinomyces viscosus',
    Brucella_abortus: 'Brucella abortus',
    Bovine_alphaherpesvirus_1: 'Bovine alphaherpesvirus 1',
    Bacillus_anthracis: 'Bacillus anthracis',
    Bordetella_bronchiseptica: 'Bordetella bronchiseptica',
    Blastomyces_dermatitidis: 'Blastomyces dermatitidis',
    Bovine_Ephemeral_Fever_virus: 'Bovine ephemeral fever virus',
    Brachyspira_hyodysenteriae: 'Brachyspira hyodysenteriae',
    Bovine_leukemia_virus: 'Bovine leukemia virus',
    Brucella_melitensis: 'Brucella melitensis',
    Bovine_papillomavirus_1__2__5: 'Bovine papillomavirus (1, 2, 5)',
    Black_queen_cell_virus: 'Black queen cell virus',
    Basidiobolus_ranarum: 'Basidiobolus ranarum',
    Brucella_suis: 'Brucella suis',
    Bovine_viral_diarrhea_virus_1: 'Bovine viral diarrhea virus 1',
    Bovine_viral_diarrhea_virus_2: 'Bovine viral diarrhea virus 2',
    Bluetongue_virus: 'Bluetongue virus',
    Chlamydia_abortus: 'Chlamydia abortus',
    Canine_adenovirus_1: 'Canine adenovirus 1',
    Canine_adenovirus_2: 'Canine adenovirus 2',
    Candida_albicans: 'Candida albicans',
    Cryptosporidium_andersoni: 'Cryptosporidium andersoni',
    Caprine_arthritis_encephalitis_virus: 'Caprine arthritis encephalitis virus',
    Candida_auris: 'Candida auris',
    Cladophialophora_bantiana: 'Cladophialophora bantiana',
    Chronic_bee_paralysis_virus: 'Chronic bee paralysis virus',
    Cryptosporidium_bovis: 'Cryptosporidium bovis',
    Coxiella_burnetii: 'Coxiella burnetii',
    Conidiobolus_coronatus: 'Conidiobolus coronatus',
    Canine_coronavirus: 'Canine coronavirus',
    Clostridium_difficile: 'Clostridium difficile',
    Chlamydophila_felis: 'Chlamydia felis',
    Cryptococcus_gattii: 'Cryptococcus gattii',
    Canid_herpesvirus_1_: 'Canid herpesvirus 1 ',
    Coccidioides_immitis: 'Coccidioides immitis',
    Campylobacter_jejuni: 'Campylobacter jejuni',
    Cryptococcus_neoformans: 'Cryptococcus neoformans',
    Canine_parainfluenza_virus: 'Canine parainfluenza virus',
    Canine_parvovirus: 'Canine parvovirus',
    Cryptosporidium_parvum: 'Cryptosporidium parvum',
    Clostridium_perfringens_B__C__D: 'Clostridium perfringens (B, C, D)',
    Clostridium_perfringens_A: 'Clostridium perfringens A',
    Clostridium_perfringens_B: 'Clostridium perfringens B',
    Clostridium_perfringens_C: 'Clostridium perfringens C',
    Clostridium_perfringens_D: 'Clostridium perfringens D',
    Corynebacterium_pseudotuberculosis: 'Corynebacterium pseudotuberculosis',
    Chlamydophila_psittaci: 'Chlamydophila psittaci',
    Claviceps_purpurea: 'Claviceps purpurea',
    Cryptosporidium_ryanae: 'Cryptosporidium ryanae',
    Classical_swine_fever_virus: 'Classical swine fever virus',
    Clostridium_tetani: 'Clostridium tetani',
    Chlamydia_trachomatis: 'Chlamydia trachomatis',
    Dactylaria_gallopava: 'Verruconis gallopava',
    Dermatophilus_congolensis_: 'Dermatophilus congolensis ',
    Dichelobacter_nodosus: 'Dichelobacter nodosus',
    Deformed_Wing_Virus: 'Deformed wing virus',
    Equid_alphaherpesvirus_1: 'Equid alphaherpesvirus 1',
    Equid_alphaherpesvirus_4: 'Equid alphaherpesvirus 4',
    Equine_arteritis_virus: 'Equine arteritis virus',
    Escherichia_coli: 'Escherichia coli',
    Enterovirus_D68: 'Enterovirus D68',
    Exophiala_dermatitidis: 'Exophiala dermatitidis',
    Equine_encephalitis_virus: 'Equine encephalitis virus',
    Epizootic_hemorrhagic_disease_virus: 'Epizootic hemorrhagic disease virus',
    Epizootic_hemorrhagic_disease_virus_2: 'Epizootic hemorrhagic disease virus 2 ',
    Equine_infectious_anemia_virus: 'Equine infectious anemia virus',
    Equine_influenza_virus: 'Equine influenza virus',
    Erysipelothrix_rhusiopathiae: 'Erysipelothrix rhusiopathiae',
    Equine_rotavirus: 'Equine rotavirus',
    Felid_alphaherpesvirus_1: 'Felid alphaherpesvirus 1',
    Feline_calicivirus: 'Feline calicivirus',
    Foot_and_mouth_disease_virus: 'Foot-and-mouth disease virus',
    Fusarium_graminearum: 'Fusarium graminearum',
    Feline_immunodeficiency_virus: 'Feline immunodeficiency virus',
    Feline_infectious_peritonitis_virus: 'Feline infectious peritonitis virus (Feline coronavirus)',
    Feline_leukemia_virus: 'Feline leukemia virus',
    Fusobacterium_necrophorum: 'Fusobacterium necrophorum',
    Feline_panleukopenia_virus: 'Feline panleukopenia virus (Feline parvovirus)',
    Fusarium_proliferatum: 'Fusarium proliferatum',
    Fusarium_verticillioides: 'Fusarium verticillioides',
    Fowlpox_virus: 'Fowlpox virus',
    Goat_pox_virus: 'Goat pox virus',
    Hepatovirus_A: 'Hepatovirus A',
    Hepatovirus_B: 'Hepatovirus B',
    Hepatovirus_C: 'Hepatovirus C',
    Histoplasma_capsulatum: 'Histoplasma capsulatum',
    Histoplasma_capsulatum_var_farciminosum: 'Histoplasma capsulatum var. farciminosum',
    Human_Immunodeficiency_Virus_1: 'Human immunodeficiency virus 1',
    Human_papillomavirus_16: 'Human papillomavirus 16',
    Human_papillomavirus_18: 'Human papillomavirus 18',
    Human_rotavirus_A: 'Human rotavirus A',
    Human_rotavirus_B: 'Human rotavirus B',
    Human_rotavirus_C: 'Human rotavirus C',
    Herpes_simplex_virus_1: 'Herpes simplex virus 1',
    Herpes_simplex_virus_2: 'Herpes simplex virus 2',
    Influenza_A: 'Influenza A',
    Influenza_A_H1N1: 'Influenza A (H1N1)',
    Influenza_A_H3N2: 'Influenza A (H3N2)',
    Influenza_B: 'Influenza B',
    Leptospira_autumnalis: 'Leptospira autumnalis',
    Leptospira_borgpetersenii: 'Leptospira borgpetersenii',
    Leptospira_grippotyphosa: 'Leptospira grippotyphosa',
    Leptospira_hyos: 'Leptospira hyos',
    Leptospira_interrogans: 'Leptospira interrogans',
    Lawsonia_intracellularis: 'Lawsonia intracellularis',
    Leptospira_kirschneri: 'Leptospira kirschneri',
    Listeria_monocytogenes: 'Listeria monocytogenes',
    Leptospira_pomona: 'Leptospira pomona',
    Lyssavirus_rabies: 'Lyssavirus rabies',
    Lumpy_skin_disease_virus: 'Lumpy skin disease virus',
    Macavirus_alcelaphinegamma1: 'Alcelaphine gammaherpesvirus 1',
    Mycobacterium_avium_subsp_Paratuberculosis: 'Mycobacterium avium subsp. Paratuberculosis',
    Mycobacterium_bovis: 'Mycobacterium bovis',
    Microsporum_canis: 'Microsporum canis',
    Morbillivirus_canis: 'Morbillivirus canis',
    Mycoplasma_capricolum_capripneumoniae: 'Mycoplasma capricolum subsp. capripneumoniae',
    Macavirus_caprinegamma2: 'Macavirus caprinegamma2',
    Mycoplasma_conjunctivae: 'Mycoplasma conjunctivae',
    Marek_s_disease_virus: 'Marek\'s disease virus',
    Mycoplasma_gallisepticum: 'Mycoplasma gallisepticum',
    Mannheimia_haemolytica_: 'Mannheimia haemolytica ',
    Mycoplasma_mycoides: 'Mycoplasma mycoides',
    Microsporum_nanum: 'Microsporum nanum',
    Macavirus_ovinegamma2: 'Macavirus ovinegamma2',
    Mycoplasma_ovis_: 'Mycoplasma ovis ',
    Malassezia_pachydermatis: 'Malassezia pachydermatis',
    Melissococcus_plutonius: 'Melissococcus plutonius',
    Mycobacterium_tuberculosis: 'Mycobacterium tuberculosis',
    Nosema_apis: 'Nosema apis',
    Nocardia_asteroides: 'Nocardia asteroides',
    Nocardia_brasiliensis: 'Nocardia brasiliensis',
    Newcastle_disease_virus: 'Newcastle disease virus',
    Norovirus_GI: 'Norovirus GI',
    Neisseria_gonorrhoeae: 'Neisseria gonorrhoeae',
    Norovirus_GV: 'Norovirus GV',       
    Neisseria_meningitidis: 'Neisseria meningitidis',
    Neorickettsia_risticii: 'Neorickettsia risticii',
    Orf_virus: 'Orf virus',
    Pseudomonas_aeruginosa: 'Pseudomonas aeruginosa',
    Pithomyces_chartarum: 'Pseudopithomyces chartarum',
    Porcine_circovirus_type_2_: 'Porcine circovirus type 2 ',
    Peste_des_petits_ruminants_virus: 'Peste des petits ruminants virus',
    Porcine_epidemic_diarrhea_virus: 'Porcine epidemic diarrhea virus',
    Paenibacillus_larvae: 'Paenibacillus larvae',
    Pasteurella_multocida: 'Pasteurella multocida',
    Penicillium_puberulum: 'Penicillium puberulum',
    Porcine_reproductive_and_respiratory_syndrome_virus_1: 'Porcine reproductive and respiratory syndrome virus 1',
    Porcine_reproductive_and_respiratory_syndrome_virus_2: 'Porcine reproductive and respiratory syndrome virus 2',
    Rhodococcus_Prescotella_equi: 'Rhodococcus equi',
    Rotavirus_A: 'Rotavirus A',
    Rotavirus_B: 'Rotavirus B',
    Rotavirus_C: 'Rotavirus C',
    Rotavirus_E: 'Rotavirus E',
    Rinderpest_virus: 'Rinderpest virus',
    Streptococcus_agalactiae: 'Streptococcus agalactiae',
    Salmonella_agona: 'Salmonella agona',
    Suid_alphaherpesvirus_1: 'Suid alphaherpesvirus 1',
    Staphylococcus_aureus: 'Staphylococcus aureus',
    Streptococcus_canis: 'Streptococcus canis',
    Schaalia_canis_Actinomyces_canis: 'Schaalia canis',
    Salmonella_choleraesuis: 'Salmonella choleraesuis',
    Salmonella_dublin: 'Salmonella dublin',
    Shigella_dysenteriae: 'Shigella dysenteriae',
    Salmonella_enteritidis: 'Salmonella enterica serovar Enteritidis',
    Streptococcus_equi_subsp_Equi: 'Streptococcus equi subsp. Equi',
    Streptococcus_equi_subsp_Zooepidemicus: 'Streptococcus equi subsp. Zooepidemicus',
    Staphylococcus_felis_: 'Staphylococcus felis ',
    Shigella_flexneri: 'Shigella flexneri',
    Staphylococcus_hyicus: 'Staphylococcus hyicus',
    Swine_influenza_virus_H1N1: 'Swine influenza virus (H1N1)',
    Swine_influenza_virus_H3N2: 'Swine influenza virus (H3N2)',
    Staphylococcus_intermedius: 'Staphylococcus intermedius',
    Salmonella_newport: 'Salmonella newport',
    Streptococcus_pneumoniae: 'Streptococcus pneumoniae',
    Staphylococcus_pseudintermedius: 'Staphylococcus pseudintermedius',
    Salmonella_pullorum: 'Salmonella pullorum',
    Sporothrix_schenckii: 'Sporothrix schenckii',
    Shigella_sonnei: 'Shigella sonnei',
    Streptococcus_suis_1__2__14__24: 'Streptococcus suis (1, 2, 14, 24)',
    Salmonella_typhimurium: 'Salmonella enterica serovar Typhimurium',
    Schmallenberg_virus: 'Schmallenberg virus',
    Sheeppox_virus: 'Sheeppox virus',
    Sacbrood_virus: 'Sacbrood virus',
    Tremovirus_A: 'Tremovirus A',
    Trichophyton_equinum: 'Trichophyton equinum',
    Transmissible_gastroenteritis_virus: 'Transmissible gastroenteritis virus',
    Trichophyton_mentagrophytes: 'Trichophyton mentagrophytes',
    Treponema_pallidum: 'Treponema pallidum',
    Trichophyton_rubrum: 'Trichophyton rubrum',
    Trichophyton_verrucosum: 'Trichophyton verrucosum',
    Visna_maedi_virus: 'Visna-maedi virus',
    Varicella_zoster_virus_Human_alphaherpesvirus_3: 'Varicella-zoster virus (Human alphaherpesvirus 3) ',
    West_Nile_virus: 'West Nile virus',
    SARS_CoV_2: 'SARS-CoV-2',
    Coxsackievirus: 'Coxsackievirus',

}












